<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trbac" nsURI="https://vanderhighway.com/trbac/2020" nsPrefix="trbac">
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demarcations" upperBound="-1"
        eType="#//Demarcation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1"
        eType="#//Permission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        eType="#//Session" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" eType="#//Schedule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="UR" upperBound="-1" eType="#//Role"
        eOpposite="#//Role/RU"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="US" upperBound="-1" eType="#//Session"
        eOpposite="#//Session/SU"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RU" upperBound="-1" eType="#//User"
        eOpposite="#//User/UR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RD" upperBound="-1" eType="#//Demarcation"
        eOpposite="#//Demarcation/DR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="juniors" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/seniors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seniors" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/juniors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Demarcation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DR" upperBound="-1" eType="#//Role"
        eOpposite="#//Role/RD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DP" upperBound="-1" eType="#//Permission"
        eOpposite="#//Permission/PD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subdemarcations" upperBound="-1"
        eType="#//Demarcation" eOpposite="#//Demarcation/superdemarcations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superdemarcations" upperBound="-1"
        eType="#//Demarcation" eOpposite="#//Demarcation/subdemarcations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PD" upperBound="-1" eType="#//Demarcation"
        eOpposite="#//Demarcation/DP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Session">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SU" upperBound="-1" eType="#//User"
        eOpposite="#//User/US"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="starttime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endtime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dayschedule" eType="#//DaySchedule"
        eOpposite="#//DaySchedule/ranges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedulerange" upperBound="-1"
        eType="#//ScheduleRange" eOpposite="#//ScheduleRange/range"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaySchedule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" upperBound="-1"
        eType="#//Range" eOpposite="#//Range/dayschedule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduleranges" upperBound="-1"
        eType="#//ScheduleRange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dayschedules" upperBound="-1"
        eType="#//DaySchedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangegroups" upperBound="-1"
        eType="#//RangeGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeekdaySchedule" eSuperTypes="#//DaySchedule"/>
  <eClassifiers xsi:type="ecore:EClass" name="YeardaySchedule" eSuperTypes="#//DaySchedule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" upperBound="-1"
        eType="#//Range" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="starttime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endtime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" upperBound="-1"
        eType="#//Range" eOpposite="#//Range/schedulerange"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
